#!/bin/bash

set -e

_add_line() {
    local check="$1"
    local line="$2"
    local file="$3"
    if ! grep -q "$check" "$file"; then
        echo "$line" >> "$file"
    fi
}

_log() {
    local logfile=/var/log/mail.log
    if [ ! -f $logfile ]; then
        touch $logfile
        chmod 640 $logfile
    fi
    echo "$(date '+%b %e %H:%I:%S') $(hostname) entrypoint[$$]: $1" >> $logfile
}

_stop() {
    /etc/init.d/postfix stop
    /etc/init.d/rsyslog stop
    _log "Docker entrypoint stop"
}

trap "_stop" SIGINT SIGTERM SIGHUP

_log "Docker entrypoint start"

routes=$(ip route | grep -v default | cut -d' ' -f1)
if [ -n "$routes" ]; then
    /usr/sbin/postconf -e mynetworks="127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 $routes"
    /usr/sbin/postconf -e inet_interfaces=all
fi

if [ -n "$HOST" ]; then /usr/sbin/postconf -e myhostname=$HOST; fi
if [ -n "$DOMAIN" ]; then /usr/sbin/postconf -e mydomain=$DOMAIN; fi
if [ -n "$MAILNAME" ]; then echo $MAILNAME > /etc/mailname; fi

# Email size limits
if [ -n "$MESSAGE_SIZE_LIMIT" ]; then
    /usr/sbin/postconf -e message_size_limit=$MESSAGE_SIZE_LIMIT
fi

# Mail relay host
if [ -n "$MAIL_RELAY_HOST" ] && [ -z "$MAIL_RELAY_PORT" ]; then
    /usr/sbin/postconf -e relayhost=$MAIL_RELAY_HOST;
fi
if [ -n "$MAIL_RELAY_HOST" ] && [ -n "$MAIL_RELAY_PORT" ]; then
    /usr/sbin/postconf -e relayhost="$MAIL_RELAY_HOST:$MAIL_RELAY_PORT";
fi
if [ -n "$MAIL_RELAY_HOST" ] && [ -n "$MAIL_RELAY_USER" ] && [ -n "$MAIL_RELAY_PASS" ]; then
    _add_line "$MAIL_RELAY_HOST" "$MAIL_RELAY_HOST $MAIL_RELAY_USER:$MAIL_RELAY_PASS" /etc/postfix/sasl_passwd
    /usr/sbin/postmap /etc/postfix/sasl_passwd
fi

# Configure SMTPS wrapping if port is 465
if [ "$MAIL_RELAY_PORT" == "465" ]; then
    /usr/sbin/postconf -e smtp_tls_wrappermode=yes
    /usr/sbin/postconf -e smtp_tls_security_level=encrypt
fi

# Force to send all emails to one email address
if [ -n "$MAIL_VIRTUAL_FORCE_TO" ]; then
    _add_line "$MAIL_VIRTUAL_FORCE_TO" "/.+@.+/ $MAIL_VIRTUAL_FORCE_TO" /etc/postfix/virtual_regexp
    /usr/sbin/postmap /etc/postfix/virtual_regexp
fi

# Define some virtual email_to addresses
if [ -n "$MAIL_VIRTUAL_DEFAULT" ] && [ -n "$MAIL_VIRTUAL_ADDRESSES" ]; then
    for addr in $MAIL_VIRTUAL_ADDRESSES; do
        _add_line "$addr" "$addr $MAIL_VIRTUAL_DEFAULT" /etc/postfix/virtual
    done
    /usr/sbin/postmap /etc/postfix/virtual
fi

# Define canonical and non-canonical sender domain
if [ -n "$MAIL_CANONICAL_DOMAINS" ]; then
    for domain in $MAIL_CANONICAL_DOMAINS; do
        _add_line "{1}@$domain" "/^(.+)@${domain//\./\\.}$/ \${1}@$domain" /etc/postfix/sender_canonical_regexp
    done
    /usr/sbin/postmap /etc/postfix/sender_canonical_regexp
fi

if [ -n "$MAIL_NON_CANONICAL_DEFAULT" ]; then
    prefix='noreply+'
    if [ -n "$MAIL_NON_CANONICAL_PREFIX" ]; then
        prefix=$MAIL_NON_CANONICAL_PREFIX
    fi
    _add_line "{2}@$MAIL_NON_CANONICAL_DEFAULT" "/^(.+)@(.+)$/ $prefix\${1}-\${2}@$MAIL_NON_CANONICAL_DEFAULT" /etc/postfix/sender_canonical_regexp
    /usr/sbin/postmap /etc/postfix/sender_canonical_regexp
fi

# Make sure no permission problems happen
/usr/sbin/postfix set-permissions

_log "Docker entrypoint configured"

# Start syslog daemon
/etc/init.d/rsyslog start

# Start Postfix daemon
/etc/init.d/postfix start

$@ & wait ${!}
