#!/bin/bash

set -e

user=test
from_name='Test'
from_email=$1
to_name='Your name'
to_email=$2
file=/tmp/emailtest.eml

if [ -z "$from_email" ] || [ -z "$to_email" ]; then
    echo "Usage: test <email_from> <email_to>"
    exit 1
fi

cat > $file << EOL
Subject: Email test for $HOST.$DOMAIN
From: $from_name <$from_email>
To: $to_name <$to_email>
Content-Type: text/plain; charset=UTF-8

This is a test email for server $HOST.$DOMAIN.
You do not have to do anything, but remove it.
Thanks

EOL

sendmail -f $user $to_email < $file
sleep 5
tail /var/log/syslog
postqueue -p
